version: '3.8'
services:
    apache:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 8000:80
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: phpcomments
            DB_USERNAME: phpuser
            DB_PASSWORD: test456
    db:
        container_name: php-db
        image: mysql:8.0
        restart: unless-stopped
        command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
        environment:
            MYSQL_ROOT_PASSWORD: test123
            MYSQL_DATABASE: phpcomments
            MYSQL_USER: phpuser
            MYSQL_PASSWORD: test456
        ports:
            - "9906:3306"
