CREATE TABLE IF NOT EXISTS `comments`(
    id INT AUTO_INCREMENT PRIMARY KEY,
    text TEXT,
    author VARCHAR(60) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
    CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
